frontend_index:
  path: '/{reactRouting}'
  defaults: { _controller: App\Controller\FrontEndController::index }
  requirements:
    reactRouting: "^((?!api).)*$"

login:
  path:     /api/auth/login
  methods:  [POST]

app.swagger_ui:
  path: /api/doc
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger_ui }
